<a href="https://colab.research.google.com/github/Despectinator/AIML-Internship-Muhammad-Ali/blob/main/Lab_06_MuhammadAli.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 6 (Week 2 — Lab 1): Introduction to Machine Learning

Welcome to Week 2! In this lab you will practice the foundational steps of every machine learning project: loading data, splitting it into training and test sets, and preparing it for models to learn from.

**For detailed theory on ML concepts, overfitting, underfitting, and why train-test splits matter, see the Lab 6 PDF and Learning Resources.**

This notebook focuses on the practical, hands-on workflow.

## Example 1: Loading & Exploring Data

We'll use the Iris dataset — a classic dataset with measurements of 150 iris flowers across three species.

In [1]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

# Load the Iris dataset
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]

print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())

Dataset shape: (150, 5)

First 5 rows:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


In [2]:
print("Column names:")
print(df.columns.tolist())
print("\nData types:")
print(df.dtypes)
print("\nTarget classes:")
print(df['species'].value_counts())

Column names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'species']

Data types:
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
species               object
dtype: object

Target classes:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64


## Example 2: Train-Test Split

The most important step: split your data so you can train on one part and test on another (unseen) part.

In [3]:
from sklearn.model_selection import train_test_split

X = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set size:", X_train.shape[0])
print("Test set size:", X_test.shape[0])
print("\nTraining set - first 3 rows:")
print(X_train.head(3))

Training set size: 120
Test set size: 30

Training set - first 3 rows:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
15                5.7               4.4                1.5               0.4
65                6.7               3.1                4.4               1.4


## Example 3: Feature Scaling

When features are on different scales, models learn better if you standardize them.

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Original training data (first 3 rows):")
print(X_train.head(3))
print("\nScaled training data (first 3 rows):")
print(X_train_scaled[:3])
print("\nScaled data - mean (should be ~0):", X_train_scaled.mean())
print("Scaled data - std dev (should be ~1):", X_train_scaled.std())

Original training data (first 3 rows):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
15                5.7               4.4                1.5               0.4
65                6.7               3.1                4.4               1.4

Scaled training data (first 3 rows):
[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]]

Scaled data - mean (should be ~0): -5.181040781584064e-17
Scaled data - std dev (should be ~1): 0.9999999999999999


## Practice Exercise 1: Train-Test Split with Different Test Size

**Exercise:** Split the Iris data with test_size=0.3 (30% for testing) instead of 0.2. Print the new sizes.

In [6]:
### YOUR CODE HERE ###
from sklearn.model_selection import train_test_split

X = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
y = df['species']

X_train_alt, X_test_alt, y_train_alt, y_test_alt = train_test_split(X, y, test_size=0.3, random_state=42)

print("\nTraining set ")
print(X_train.head())
### END ###

print("New training set size:", X_train_alt.shape[0])
print("New test set size:", X_test_alt.shape[0])


Training set 
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
15                5.7               4.4                1.5               0.4
65                6.7               3.1                4.4               1.4
11                4.8               3.4                1.6               0.2
42                4.4               3.2                1.3               0.2
New training set size: 105
New test set size: 45


**Expected Output:**
```
New training set size: 105
New test set size: 45
```

## Practice Exercise 2: Check Scaled Data Statistics

**Exercise:** After scaling the training set (as shown in Example 3), verify that the mean of each feature is close to 0 and the standard deviation is close to 1. Print both for the scaled training data.

In [11]:
### YOUR CODE HERE ###
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Original training data (first 3 rows):")
print(X_train.head(3))
print("\nScaled training data (first 3 rows):")
print(X_train_scaled[:3])

# Corrected: Print mean and std dev of X_train_scaled
print("\nScaled data - mean (should be ~0):", X_train_scaled.mean(axis=0))
print("Scaled data - std dev (should be ~1):", X_train_scaled.std(axis=0))
### END ###

Original training data (first 3 rows):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
15                5.7               4.4                1.5               0.4
65                6.7               3.1                4.4               1.4

Scaled training data (first 3 rows):
[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]]

Scaled data - mean (should be ~0): [ 1.71344420e-15 -1.66579713e-15 -2.23894977e-16 -5.73615229e-17]
Scaled data - std dev (should be ~1): [1. 1. 1. 1.]


## Practice Exercise 3: Scaling the Test Set

**Exercise:** Use the fitted scaler (from Example 3) to scale the test set X_test. Important: always use `.transform()` on test data, NOT `.fit_transform()`. Print the first 3 rows of scaled test data.

In [12]:
### YOUR CODE HERE ###
X_test_scaled_exercise = scaler.transform(X_test)
print("Scaled test data (first 3 rows):")
print(X_test_scaled_exercise[:3])
### END ###

Scaled test data (first 3 rows):
[[ 0.35451684 -0.58505976  0.55777524  0.02224751]
 [-0.13307079  1.65083742 -1.16139502 -1.17911778]
 [ 2.30486738 -1.0322392   1.8185001   1.49058286]]


## Lab Tasks

Complete the following in this notebook, below this cell.

1. **Data Inspection**: Load the Iris dataset (as shown in Example 1) and describe what you find: number of rows, columns, any missing values, and the distribution of the three species classes.
2. **Train-Test Split**: Split the Iris data into 75% training and 25% testing (different from the 80-20 split shown in examples). Print both set sizes.
3. **Feature Scaling**: Scale both the training and test sets using StandardScaler. Verify that the mean and standard deviation of the scaled training data are correct.
4. **Understanding the Workflow**: In a markdown cell, explain in 3-4 sentences why we split data into training and test sets, and why scaling features helps models learn better. Use simple language.
5. **Reflection**: Write 2-3 sentences on what you learned in this lab and what questions remain before you start building actual models next lab.

In [15]:
# Task 1

from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

# Load the Iris dataset
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]

print("All rows:")
print(df.head())


All rows:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


In [16]:
# Task 2:
from sklearn.model_selection import train_test_split

# Using the dataframe 'df' created in Task 1
X_task = df.drop('species', axis=1)
y_task = df['species']

X_train_task, X_test_task, y_train_task, y_test_task = train_test_split(X_task, y_task, test_size=0.25, random_state=42)

print(f"Training set size: {X_train_task.shape[0]}")
print(f"Test set size: {X_test_task.shape[0]}")

Training set size: 112
Test set size: 38


In [17]:
# Task 3: Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler_task = StandardScaler()

# Fit on training data, then transform both
X_train_task_scaled = scaler_task.fit_transform(X_train_task)
X_test_task_scaled = scaler_task.transform(X_test_task)

print("Scaled Training Mean (should be ~0):", X_train_task_scaled.mean(axis=0))
print("Scaled Training Std Dev (should be ~1):", X_train_task_scaled.std(axis=0))

Scaled Training Mean (should be ~0): [ 1.72282823e-15 -4.64410256e-16 -4.24263799e-16  7.07767178e-16]
Scaled Training Std Dev (should be ~1): [1. 1. 1. 1.]


In [19]:
### Task 4: Understanding the Workflow
#We split data into training and test sets to ensure we can evaluate how well our model performs on new, unseen data, which helps detect if the model is just memorizing the training examples. Scaling features is important because many machine learning algorithms calculate distances between data points; if one feature has a much larger range than others, it will dominate the learning process. By standardizing features to a similar scale, we help the model learn from all features equally and often speed up the training process.

### Task 4:

We split data into training and test sets to ensure we can evaluate how well our model performs on new, unseen data, which helps detect if the model is just memorizing the training examples. Scaling features is important because many machine learning algorithms calculate distances between data points; if one feature has a much larger range than others, it will dominate the learning process. By standardizing features to a similar scale, we help the model learn from all features equally and often speed up the training process.

### Task 5: Reflection
In this lab, I learned the standard workflow of preparing data for machine learning, specifically how to split datasets and use scikit-learn's StandardScaler. I also realized how critical it is to only 'fit' on the training data to avoid data leakage. A remaining question I have is how to choose the best split ratio for much larger or much smaller datasets.